export const VEHICLE_EXTRAS: Record<string, string[]> = {
  Basic: [
    "ABS Brakes",
    "Air Conditioning",
    "Airbags",
    "Alarm",
    "Central Locking",
    "Electric Windows",
    "Front Electric Windows",
    "Immobilizer",
    "Manual",
    "Power Steering",
    "Radio",
    "Radio/CD",
    "Radio/CD/MP3",
    "USB Input",
    "iPod Input",
    "Auxiliary Audio Input",
    "Drink Holder",
    "Full Spare Wheel",
    "Service Plan",
    "Maintenance Plan",
    "Full Service History",
    "Full Service History by Agents",
    "Balance of Factory Warranty",
  ],
  Exterior: [
    "Alloy Wheels",
    "Bullbar",
    "Canopy",
    "Locknuts",
    "Nudge Bar",
    "Rollbar",
    "Roof Rack",
    "Roof Rails",
    "Rubberized Load Body",
    "Running Boards",
    "Skylights",
    "Sunroof",
    "Towbar",
    "Winch",
    "Detachable Tow Bar",
    "Fog Lights",
    "LED Daytime Lights",
    "Headlight Washers",
    "Panoramic Roof",
  ],
  Standard: [
    "4x2",
    "4x4",
    "Automatic",
    "Automatic Start Stop",
    "Bluetooth Ready",
    "CD Multi Changer",
    "Climate Control",
    "Cruise Control",
    "Diff Lock",
    "Drink Cooler",
    "EBD Electronic Brake Distribution",
    "Electric Mirrors",
    "Electric Seats",
    "ESP Electronic Stability Program",
    "Front Wheel Drive",
    "Full House",
    "Multi-Function Steering",
    "Parking Sensors",
    "Rain Sensor",
    "Rear Air Conditioning",
    "Rear View Camera",
    "Rear Windshield Defroster",
    "Sat Nav",
    "Seat Heaters",
    "Smash and Grab Windows",
    "Steering Wheel Controls",
    "Traction Control",
    "Trip Computer",
  ],
  "Top Spec": [
    "Adaptive Cruise Control",
    "Adjustable Suspension",
    "All Wheel Drive",
    "Auto Dim Rear View Mirror",
    "Blind Spot Monitor",
    "DVD Video System",
    "Electric Memory Seats",
    "Heated Electric Mirrors",
    "Head-Up Display",
    "Keyless Go",
    "Lane Assist",
    "Leather",
    "Massage Seats",
    "Microdot",
    "Night Vision",
    "Paddle Shift",
    "Run-Flat Tyres",
    "Surround View Camera",
    "Ventilated Seats",
    "Wireless Charging",
  ],
};
